version: '3.8'
services:
  db:
    image: postgres:14.2-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
